# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuroServiceStub(object):
    """NeuroService: 神经中枢服务
    类似于游戏里的 "WorldServer"，负责分发指令和接收状态
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/agent.NeuroService/RegisterWorker',
                request_serializer=agent__pb2.WorkerInfo.SerializeToString,
                response_deserializer=agent__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/agent.NeuroService/Heartbeat',
                request_serializer=agent__pb2.Ping.SerializeToString,
                response_deserializer=agent__pb2.Pong.FromString,
                _registered_method=True)
        self.ExecuteTask = channel.unary_stream(
                '/agent.NeuroService/ExecuteTask',
                request_serializer=agent__pb2.TaskRequest.SerializeToString,
                response_deserializer=agent__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.WorkerStream = channel.stream_stream(
                '/agent.NeuroService/WorkerStream',
                request_serializer=agent__pb2.WorkerData.SerializeToString,
                response_deserializer=agent__pb2.ServerCommand.FromString,
                _registered_method=True)


class NeuroServiceServicer(object):
    """NeuroService: 神经中枢服务
    类似于游戏里的 "WorldServer"，负责分发指令和接收状态
    """

    def RegisterWorker(self, request, context):
        """1. Handshake: Worker 节点启动时向 Center 注册 (就像 NPC 上线)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """2. Heartbeat: 维持 TCP 长连接保活 (Keep-Alive)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTask(self, request, context):
        """3. TaskExecution: 核心指令通道
        Server 下发 Prompt，Worker以此流式返回 Token (Server-side Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=agent__pb2.WorkerInfo.FromString,
                    response_serializer=agent__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent__pb2.Ping.FromString,
                    response_serializer=agent__pb2.Pong.SerializeToString,
            ),
            'ExecuteTask': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=agent__pb2.TaskRequest.FromString,
                    response_serializer=agent__pb2.TaskResponse.SerializeToString,
            ),
            'WorkerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerStream,
                    request_deserializer=agent__pb2.WorkerData.FromString,
                    response_serializer=agent__pb2.ServerCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.NeuroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.NeuroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeuroService(object):
    """NeuroService: 神经中枢服务
    类似于游戏里的 "WorldServer"，负责分发指令和接收状态
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.NeuroService/RegisterWorker',
            agent__pb2.WorkerInfo.SerializeToString,
            agent__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.NeuroService/Heartbeat',
            agent__pb2.Ping.SerializeToString,
            agent__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.NeuroService/ExecuteTask',
            agent__pb2.TaskRequest.SerializeToString,
            agent__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WorkerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/agent.NeuroService/WorkerStream',
            agent__pb2.WorkerData.SerializeToString,
            agent__pb2.ServerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
