# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"[\n\nWorkerData\x12\x1b\n\x04ping\x18\x01 \x01(\x0b\x32\x0b.agent.PingH\x00\x12%\n\x06result\x18\x02 \x01(\x0b\x32\x13.agent.TaskResponseH\x00\x42\t\n\x07payload\"[\n\rServerCommand\x12\x1b\n\x04pong\x18\x01 \x01(\x0b\x32\x0b.agent.PongH\x00\x12\"\n\x04task\x18\x02 \x01(\x0b\x32\x12.agent.TaskRequestH\x00\x42\t\n\x07payload\"_\n\nWorkerInfo\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x11\n\tgpu_model\x18\x02 \x01(\t\x12\x15\n\rvram_total_mb\x18\x03 \x01(\x05\x12\x14\n\x0c\x63\x61pabilities\x18\x04 \x03(\t\"8\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bserver_time\x18\x02 \x01(\t\"\x19\n\x04Ping\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x13\n\x04Pong\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"Z\n\x0bTaskRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\"\xa8\x01\n\x0cTaskResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x31\n\x07metrics\x18\x04 \x03(\x0b\x32 .agent.TaskResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xea\x01\n\x0cNeuroService\x12<\n\x0eRegisterWorker\x12\x11.agent.WorkerInfo\x1a\x17.agent.RegisterResponse\x12%\n\tHeartbeat\x12\x0b.agent.Ping\x1a\x0b.agent.Pong\x12\x38\n\x0b\x45xecuteTask\x12\x12.agent.TaskRequest\x1a\x13.agent.TaskResponse0\x01\x12;\n\x0cWorkerStream\x12\x11.agent.WorkerData\x1a\x14.agent.ServerCommand(\x01\x30\x01\x42\x0fZ\rneuro-grid/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rneuro-grid/pb'
  _globals['_TASKRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_TASKRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_WORKERDATA']._serialized_start=22
  _globals['_WORKERDATA']._serialized_end=113
  _globals['_SERVERCOMMAND']._serialized_start=115
  _globals['_SERVERCOMMAND']._serialized_end=206
  _globals['_WORKERINFO']._serialized_start=208
  _globals['_WORKERINFO']._serialized_end=303
  _globals['_REGISTERRESPONSE']._serialized_start=305
  _globals['_REGISTERRESPONSE']._serialized_end=361
  _globals['_PING']._serialized_start=363
  _globals['_PING']._serialized_end=388
  _globals['_PONG']._serialized_start=390
  _globals['_PONG']._serialized_end=409
  _globals['_TASKREQUEST']._serialized_start=411
  _globals['_TASKREQUEST']._serialized_end=501
  _globals['_TASKRESPONSE']._serialized_start=504
  _globals['_TASKRESPONSE']._serialized_end=672
  _globals['_TASKRESPONSE_METRICSENTRY']._serialized_start=626
  _globals['_TASKRESPONSE_METRICSENTRY']._serialized_end=672
  _globals['_NEUROSERVICE']._serialized_start=675
  _globals['_NEUROSERVICE']._serialized_end=909
# @@protoc_insertion_point(module_scope)
