// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NeuroService_RegisterWorker_FullMethodName = "/agent.NeuroService/RegisterWorker"
	NeuroService_Heartbeat_FullMethodName      = "/agent.NeuroService/Heartbeat"
	NeuroService_ExecuteTask_FullMethodName    = "/agent.NeuroService/ExecuteTask"
	NeuroService_WorkerStream_FullMethodName   = "/agent.NeuroService/WorkerStream"
)

// NeuroServiceClient is the client API for NeuroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NeuroService: 神经中枢服务
// 类似于游戏里的 "WorldServer"，负责分发指令和接收状态
type NeuroServiceClient interface {
	// 1. Handshake: Worker 节点启动时向 Center 注册 (就像 NPC 上线)
	RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 2. Heartbeat: 维持 TCP 长连接保活 (Keep-Alive)
	Heartbeat(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	// 3. TaskExecution: 核心指令通道
	// Server 下发 Prompt，Worker以此流式返回 Token (Server-side Streaming)
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskResponse], error)
	WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerData, ServerCommand], error)
}

type neuroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNeuroServiceClient(cc grpc.ClientConnInterface) NeuroServiceClient {
	return &neuroServiceClient{cc}
}

func (c *neuroServiceClient) RegisterWorker(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NeuroService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neuroServiceClient) Heartbeat(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, NeuroService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neuroServiceClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NeuroService_ServiceDesc.Streams[0], NeuroService_ExecuteTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskRequest, TaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeuroService_ExecuteTaskClient = grpc.ServerStreamingClient[TaskResponse]

func (c *neuroServiceClient) WorkerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerData, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NeuroService_ServiceDesc.Streams[1], NeuroService_WorkerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerData, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeuroService_WorkerStreamClient = grpc.BidiStreamingClient[WorkerData, ServerCommand]

// NeuroServiceServer is the server API for NeuroService service.
// All implementations must embed UnimplementedNeuroServiceServer
// for forward compatibility.
//
// NeuroService: 神经中枢服务
// 类似于游戏里的 "WorldServer"，负责分发指令和接收状态
type NeuroServiceServer interface {
	// 1. Handshake: Worker 节点启动时向 Center 注册 (就像 NPC 上线)
	RegisterWorker(context.Context, *WorkerInfo) (*RegisterResponse, error)
	// 2. Heartbeat: 维持 TCP 长连接保活 (Keep-Alive)
	Heartbeat(context.Context, *Ping) (*Pong, error)
	// 3. TaskExecution: 核心指令通道
	// Server 下发 Prompt，Worker以此流式返回 Token (Server-side Streaming)
	ExecuteTask(*TaskRequest, grpc.ServerStreamingServer[TaskResponse]) error
	WorkerStream(grpc.BidiStreamingServer[WorkerData, ServerCommand]) error
	mustEmbedUnimplementedNeuroServiceServer()
}

// UnimplementedNeuroServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNeuroServiceServer struct{}

func (UnimplementedNeuroServiceServer) RegisterWorker(context.Context, *WorkerInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedNeuroServiceServer) Heartbeat(context.Context, *Ping) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNeuroServiceServer) ExecuteTask(*TaskRequest, grpc.ServerStreamingServer[TaskResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedNeuroServiceServer) WorkerStream(grpc.BidiStreamingServer[WorkerData, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method WorkerStream not implemented")
}
func (UnimplementedNeuroServiceServer) mustEmbedUnimplementedNeuroServiceServer() {}
func (UnimplementedNeuroServiceServer) testEmbeddedByValue()                      {}

// UnsafeNeuroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NeuroServiceServer will
// result in compilation errors.
type UnsafeNeuroServiceServer interface {
	mustEmbedUnimplementedNeuroServiceServer()
}

func RegisterNeuroServiceServer(s grpc.ServiceRegistrar, srv NeuroServiceServer) {
	// If the following call panics, it indicates UnimplementedNeuroServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NeuroService_ServiceDesc, srv)
}

func _NeuroService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeuroServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NeuroService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeuroServiceServer).RegisterWorker(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeuroService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeuroServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NeuroService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeuroServiceServer).Heartbeat(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeuroService_ExecuteTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NeuroServiceServer).ExecuteTask(m, &grpc.GenericServerStream[TaskRequest, TaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeuroService_ExecuteTaskServer = grpc.ServerStreamingServer[TaskResponse]

func _NeuroService_WorkerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NeuroServiceServer).WorkerStream(&grpc.GenericServerStream[WorkerData, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeuroService_WorkerStreamServer = grpc.BidiStreamingServer[WorkerData, ServerCommand]

// NeuroService_ServiceDesc is the grpc.ServiceDesc for NeuroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NeuroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.NeuroService",
	HandlerType: (*NeuroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _NeuroService_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NeuroService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTask",
			Handler:       _NeuroService_ExecuteTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WorkerStream",
			Handler:       _NeuroService_WorkerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
