// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerData_Ping
	//	*WorkerData_Result
	Payload       isWorkerData_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerData) Reset() {
	*x = WorkerData{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerData) ProtoMessage() {}

func (x *WorkerData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerData.ProtoReflect.Descriptor instead.
func (*WorkerData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerData) GetPayload() isWorkerData_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerData) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*WorkerData_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *WorkerData) GetResult() *TaskResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerData_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isWorkerData_Payload interface {
	isWorkerData_Payload()
}

type WorkerData_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type WorkerData_Result struct {
	Result *TaskResponse `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // 推理结果
}

func (*WorkerData_Ping) isWorkerData_Payload() {}

func (*WorkerData_Result) isWorkerData_Payload() {}

type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerCommand_Pong
	//	*ServerCommand_Task
	Payload       isServerCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetPayload() isServerCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerCommand) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerCommand_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerCommand) GetTask() *TaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerCommand_Task); ok {
			return x.Task
		}
	}
	return nil
}

type isServerCommand_Payload interface {
	isServerCommand_Payload()
}

type ServerCommand_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ServerCommand_Task struct {
	Task *TaskRequest `protobuf:"bytes,2,opt,name=task,proto3,oneof"` // 下发任务
}

func (*ServerCommand_Pong) isServerCommand_Payload() {}

func (*ServerCommand_Task) isServerCommand_Payload() {}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`             // UUID
	GpuModel      string                 `protobuf:"bytes,2,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`             // e.g., "RTX 4070 Ti Super"
	VramTotalMb   int32                  `protobuf:"varint,3,opt,name=vram_total_mb,json=vramTotalMb,proto3" json:"vram_total_mb,omitempty"` // 显存大小，用于调度权重计算
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                     // 支持的模型 ["llama3", "mistral"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *WorkerInfo) GetVramTotalMb() int32 {
	if x != nil {
		return x.VramTotalMb
	}
	return 0
}

func (x *WorkerInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    string                 `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // TraceID
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // 指定模型
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`                        // 原始 Prompt
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`            // 随机性参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type TaskResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Content   string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                 // 生成的 Token (或者 Error Message)
	IsFinal   bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // 是否结束 (End of Stream)
	// 性能遥测数据 (类似游戏里的 FPS/Ping)
	Metrics       map[string]string `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"tps": "45.2", "latency": "20ms"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TaskResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"i\n" +
	"\n" +
	"WorkerData\x12!\n" +
	"\x04ping\x18\x01 \x01(\v2\v.agent.PingH\x00R\x04ping\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x13.agent.TaskResponseH\x00R\x06resultB\t\n" +
	"\apayload\"g\n" +
	"\rServerCommand\x12!\n" +
	"\x04pong\x18\x01 \x01(\v2\v.agent.PongH\x00R\x04pong\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x12.agent.TaskRequestH\x00R\x04taskB\t\n" +
	"\apayload\"\x8e\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tgpu_model\x18\x02 \x01(\tR\bgpuModel\x12\"\n" +
	"\rvram_total_mb\x18\x03 \x01(\x05R\vvramTotalMb\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"M\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime\"#\n" +
	"\x04Ping\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"\x85\x01\n" +
	"\vTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\"\xda\x01\n" +
	"\fTaskResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12:\n" +
	"\ametrics\x18\x04 \x03(\v2 .agent.TaskResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xea\x01\n" +
	"\fNeuroService\x12<\n" +
	"\x0eRegisterWorker\x12\x11.agent.WorkerInfo\x1a\x17.agent.RegisterResponse\x12%\n" +
	"\tHeartbeat\x12\v.agent.Ping\x1a\v.agent.Pong\x128\n" +
	"\vExecuteTask\x12\x12.agent.TaskRequest\x1a\x13.agent.TaskResponse0\x01\x12;\n" +
	"\fWorkerStream\x12\x11.agent.WorkerData\x1a\x14.agent.ServerCommand(\x010\x01B\x0fZ\rneuro-grid/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agent_proto_goTypes = []any{
	(*WorkerData)(nil),       // 0: agent.WorkerData
	(*ServerCommand)(nil),    // 1: agent.ServerCommand
	(*WorkerInfo)(nil),       // 2: agent.WorkerInfo
	(*RegisterResponse)(nil), // 3: agent.RegisterResponse
	(*Ping)(nil),             // 4: agent.Ping
	(*Pong)(nil),             // 5: agent.Pong
	(*TaskRequest)(nil),      // 6: agent.TaskRequest
	(*TaskResponse)(nil),     // 7: agent.TaskResponse
	nil,                      // 8: agent.TaskResponse.MetricsEntry
}
var file_agent_proto_depIdxs = []int32{
	4, // 0: agent.WorkerData.ping:type_name -> agent.Ping
	7, // 1: agent.WorkerData.result:type_name -> agent.TaskResponse
	5, // 2: agent.ServerCommand.pong:type_name -> agent.Pong
	6, // 3: agent.ServerCommand.task:type_name -> agent.TaskRequest
	8, // 4: agent.TaskResponse.metrics:type_name -> agent.TaskResponse.MetricsEntry
	2, // 5: agent.NeuroService.RegisterWorker:input_type -> agent.WorkerInfo
	4, // 6: agent.NeuroService.Heartbeat:input_type -> agent.Ping
	6, // 7: agent.NeuroService.ExecuteTask:input_type -> agent.TaskRequest
	0, // 8: agent.NeuroService.WorkerStream:input_type -> agent.WorkerData
	3, // 9: agent.NeuroService.RegisterWorker:output_type -> agent.RegisterResponse
	5, // 10: agent.NeuroService.Heartbeat:output_type -> agent.Pong
	7, // 11: agent.NeuroService.ExecuteTask:output_type -> agent.TaskResponse
	1, // 12: agent.NeuroService.WorkerStream:output_type -> agent.ServerCommand
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerData_Ping)(nil),
		(*WorkerData_Result)(nil),
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerCommand_Pong)(nil),
		(*ServerCommand_Task)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
